export const COLOR_PRESETS = {
  calendar: [
    { value: '', label: 'Omit — do not pass color' },
    { value: 'blue', label: 'Named — blue (valid on iOS)' },
    { value: 'orange', label: 'Named — orange (valid on iOS)' },
    { value: 'indigo', label: 'Named — indigo (valid on iOS)' },
    { value: '#007AFF', label: 'Hex — #007AFF (valid)' },
    { value: '#0000FF', label: 'Hex — #0000FF (valid)' },
    { value: '#FF0000', label: 'Hex — #FF0000 (valid)' },
    { value: '#00FF0080', label: 'Hex — #00FF0080 (valid)' },
    { value: '#0000ff', label: 'Hex lowercase — #0000ff (valid)' },
    { value: '#6750A4', label: 'Hex — #6750A4 (valid)' },
    { value: 'navy', label: 'Named — navy (invalid)' },
    { value: '0000FF', label: 'Missing # — 0000FF (invalid)' },
    { value: '#F00', label: 'Too short — #F00 (invalid)' },
    { value: '#FF0000FF00', label: 'Too long — #FF0000FF00 (invalid)' },
    { value: '#ZZ0000', label: 'Non-hex — #ZZ0000 (invalid)' },
  ],
  event: [
    { value: '', label: 'Omit — do not pass color' },
    { value: '#007AFF', label: 'Hex — #007AFF (valid)' },
    { value: '#0000FF', label: 'Hex — #0000FF (valid)' },
    { value: '#FF0000', label: 'Hex — #FF0000 (valid)' },
    { value: '#00FF0080', label: 'Hex — #00FF0080 (valid)' },
    { value: '#0000ff', label: 'Hex lowercase — #0000ff (valid)' },
    { value: '#6750A4', label: 'Hex — #6750A4 (valid)' },
    { value: 'blue', label: 'Named — blue (omitted; not hex)' },
    { value: 'navy', label: 'Named — navy (omitted; not hex)' },
    { value: '0000FF', label: 'Missing # — 0000FF (omitted; not hex)' },
    { value: '#F00', label: 'Too short — #F00 (sent; invalid)' },
    { value: '#FF0000FF00', label: 'Too long — #FF0000FF00 (sent; invalid)' },
    { value: '#ZZ0000', label: 'Non-hex — #ZZ0000 (sent; invalid)' },
  ],
  list: [
    { value: '', label: 'Omit — do not pass color' },
    { value: 'blue', label: 'Named — blue (valid)' },
    { value: 'orange', label: 'Named — orange (valid)' },
    { value: 'indigo', label: 'Named — indigo (valid)' },
    { value: 'teal', label: 'Named — teal (valid)' },
    { value: '#007AFF', label: 'Hex — #007AFF (valid)' },
    { value: '#FF0000', label: 'Hex — #FF0000 (valid)' },
    { value: '#00FF0080', label: 'Hex — #00FF0080 (valid)' },
    { value: 'navy', label: 'Named — navy (invalid)' },
    { value: '0000FF', label: 'Missing # — 0000FF (invalid)' },
    { value: '#F00', label: 'Too short — #F00 (invalid)' },
    { value: '#ZZ0000', label: 'Non-hex — #ZZ0000 (invalid)' },
  ],
};
